name: product_list
description: Product List with Sorting and Searching
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  bloc_concurrency: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  bloc_test: ^9.1.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
